// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpMw3KuXa91gIaueUxDwvr0PR5c4rUl78',
    appId: '1:205177497403:web:db8d75229befb4684af91e',
    messagingSenderId: '205177497403',
    projectId: 'zoom-clone-83125',
    authDomain: 'zoom-clone-83125.firebaseapp.com',
    storageBucket: 'zoom-clone-83125.firebasestorage.app',
    measurementId: 'G-LFQXRJCNKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdLyhyNLBAWLNcPt8Zmj4tAt_rPZ_H9QI',
    appId: '1:304263618463:android:54a63d525dad769fd427aa',
    messagingSenderId: '304263618463',
    projectId: 'device-streaming-f1dfcfdd',
    databaseURL:
        'https://device-streaming-f1dfcfdd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'device-streaming-f1dfcfdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqNodjYMmfi6k4buUxMaGKEeZjDjc_3pQ',
    appId: '1:304263618463:ios:849cf8d49eb49d13d427aa',
    messagingSenderId: '304263618463',
    projectId: 'device-streaming-f1dfcfdd',
    databaseURL:
        'https://device-streaming-f1dfcfdd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'device-streaming-f1dfcfdd.firebasestorage.app',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqNodjYMmfi6k4buUxMaGKEeZjDjc_3pQ',
    appId: '1:304263618463:ios:849cf8d49eb49d13d427aa',
    messagingSenderId: '304263618463',
    projectId: 'device-streaming-f1dfcfdd',
    databaseURL:
        'https://device-streaming-f1dfcfdd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'device-streaming-f1dfcfdd.firebasestorage.app',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBOUhaMG8ZAhR72npGQP1kjAKBtFpb3dc',
    appId: '1:304263618463:web:958d03d9ce25ad2cd427aa',
    messagingSenderId: '304263618463',
    projectId: 'device-streaming-f1dfcfdd',
    authDomain: 'device-streaming-f1dfcfdd.firebaseapp.com',
    databaseURL:
        'https://device-streaming-f1dfcfdd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'device-streaming-f1dfcfdd.firebasestorage.app',
  );
}
